### ISSUE TITLE
Anyone can fire a tweet

### ISSUE THREAD

**Issue by AdminRAT** [phonyfakeorreal/TweetIt#1]
From testing this using my account and an alt, I found out that anyone can fire a tweet using the bot. It would be nice if there was a bot owner restriction to this so that the owner can use it, and no one else could use it.

**Comment by AdminRAT** [comment]
or actually, trying different pieces of code, there is one way that I tried that worked

I replaced
if (!message.author.bot)
with
if (message.author.id == 'YOURIDHERE')

**Comment by kalebmmm** [comment]
That's the whole point, it was a social experiment.
